# Generated by Django 5.0.6 on 2024-06-03 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_staff_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Staff', 'verbose_name_plural': 'Staffs'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
