# Generated by Django 5.0.4 on 2024-06-10 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_reservatio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reservatio',
        ),
    ]
