# Generated by Django 5.0.4 on 2024-06-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_reservatio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='duration',
            new_name='guests',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='student',
        ),
        migrations.AddField(
            model_name='reservation',
            name='class_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='special_requests',
            field=models.TextField(blank=True),
        ),
    ]
