# Generated by Django 5.0.4 on 2024-06-20 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_reservation_staff_id_reservation_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='staff_id',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='student_id',
            new_name='student',
        ),
    ]
