# Generated by Django 5.0.4 on 2024-06-20 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_staff_id_reservation_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.staff'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.student'),
        ),
    ]
