# Generated by Django 5.0.4 on 2024-06-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_reservation_staff_alter_reservation_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(default='23:59:59'),
        ),
    ]
