# Generated by Django 5.0.4 on 2024-06-21 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_reservation_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='end_time',
        ),
    ]
