# Generated by Django 5.0.6 on 2024-06-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_reservation_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='id',
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Facaulty',
        ),
    ]
