# Generated by Django 5.0.6 on 2024-06-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_facility_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='class_code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
