# Generated by Django 5.0.6 on 2024-06-22 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_delete_assetmanager_remove_reviews_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.staff'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
    ]
