# Generated by Django 5.0.6 on 2024-06-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_reviews_review_id_alter_reviews_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='facility_class_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
