# Generated by Django 5.0.6 on 2024-06-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_reviews_facility_class_code_alter_reviews_review_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='facility_class_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
