# Generated by Django 5.0.4 on 2024-05-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='venu_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
