# Generated by Django 5.0.6 on 2024-06-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_reservation_venu_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='venu_image',
        ),
        migrations.AddField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
