# Generated by Django 5.0.6 on 2024-06-03 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_staff_username_alter_student_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
