# Generated by Django 5.0.6 on 2024-06-04 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_staff_username_remove_student_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='is_staff',
        ),
    ]
